/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AeVideoComponent {
    /**
    * Mute the video
    */
    'muted': boolean;
    /**
    * The image shown while the video is loading
    */
    'poster': string;
    /**
    * The video src
    */
    'src': string;
  }
}

declare global {


  interface HTMLAeVideoComponentElement extends Components.AeVideoComponent, HTMLStencilElement {}
  var HTMLAeVideoComponentElement: {
    prototype: HTMLAeVideoComponentElement;
    new (): HTMLAeVideoComponentElement;
  };
  interface HTMLElementTagNameMap {
    'ae-video-component': HTMLAeVideoComponentElement;
  }
}

declare namespace LocalJSX {
  interface AeVideoComponent extends JSXBase.HTMLAttributes<HTMLAeVideoComponentElement> {
    /**
    * Mute the video
    */
    'muted'?: boolean;
    /**
    * The image shown while the video is loading
    */
    'poster'?: string;
    /**
    * The video src
    */
    'src'?: string;
  }

  interface IntrinsicElements {
    'ae-video-component': AeVideoComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


